"""empty message

Revision ID: 337764315bb0
Revises: 
Create Date: 2023-11-13 18:51:29.708007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337764315bb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('kategori', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magaza',
    sa.Column('adi', sa.String(), nullable=False),
    sa.Column('adres', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=False),
    sa.Column('yetkili', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musteri',
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('soyad', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=False),
    sa.Column('adres', sa.String(), nullable=False),
    sa.Column('fotograf', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun',
    sa.Column('urun_kodu', sa.String(), nullable=False),
    sa.Column('adi', sa.String(), nullable=False),
    sa.Column('fiyati', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.String(), nullable=False),
    sa.Column('fotograf', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urun_kodu')
    )
    op.create_table('alis_hareketleri',
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=False),
    sa.Column('birim_fiyat', sa.Float(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satis_modeli',
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=False),
    sa.Column('birim_fiyat', sa.Float(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siparis',
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('magaza_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['magaza_id'], ['magaza.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun_ozellik',
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('ozellik', sa.String(), nullable=False),
    sa.Column('deger', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['urun_id'], ['magaza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siparis_urun',
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('adet', sa.Float(), nullable=False),
    sa.Column('birim_fiyat', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparis.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yorum',
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('yorum', sa.String(), nullable=True),
    sa.Column('puan', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparis.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yorum')
    op.drop_table('siparis_urun')
    op.drop_table('urun_ozellik')
    op.drop_table('siparis')
    op.drop_table('satis_modeli')
    op.drop_table('alis_hareketleri')
    op.drop_table('urun')
    op.drop_table('musteri')
    op.drop_table('magaza')
    op.drop_table('kategori')
    # ### end Alembic commands ###
